trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  displayName: 'Download JMeter script and test data'
  name: testFiles
  inputs:
    secureFile: 'testfirst.jmx'
    retryCount: 3

- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'
    addToPath: true

- script: |
    jmeter -n -t $(testFiles.secureFilePath) -l testJmeter.jtl -e -o TestResult.html
  displayName: 'Run JMeter test'

- task: PublishTestResults@2
  displayName: 'Publish JMeter test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'testJmeter.jtl'
    testRunTitle: 'JMeter Test Results'

- task: PublishBuildArtifacts@1
  displayName: 'Publish JMeter Test Report'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/TestResult.html'
    ArtifactName: 'JMeterTestReport'
